name: yelpexplorer
description: YelpExplorer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  cupertino_icons: ^0.1.3
  equatable: ^2.0.3
  get_it: ^7.2.0
  graphql_flutter: ^5.0.0
  http: ^0.13.3
  intl: ^0.17.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  bloc_test: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - config/app_config.json
