name: pull_request

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter config --enable-web
#      - run: flutter  config --enable-linux-desktop
#      - run: flutter  config --enable-macos-desktop
#      - run: flutter  config --enable-windows-desktop

      - run: flutter pub get

      - name: Add config file
        run: |
          mkdir config
          cd config
          echo '{"api_key": "${{secrets.api_key}}"}' > app_config.json

      - run: flutter build apk --release
      - run: flutter build ios --release --no-codesign
      - run: flutter build web --release

      - run: flutter test
